# Generated by Django 6.0.3 on 2026-04-06 17:13

import django.db.models.deletion
import infrastructure.persistence.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankConnectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('blz', models.CharField(max_length=8)),
                ('url', models.URLField()),
                ('user_id', models.CharField(max_length=255)),
                ('customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('pin', infrastructure.persistence.fields.EncryptedCharField(max_length=1024)),
            ],
            options={
                'db_table': 'bank_connections',
            },
        ),
        migrations.CreateModel(
            name='AccountMappingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_iban', models.CharField(max_length=34)),
                ('actual_budget_id', models.CharField(max_length=255)),
                ('actual_account_id', models.CharField(max_length=255)),
                ('budget_encryption_password', infrastructure.persistence.fields.EncryptedCharField(blank=True, default='', max_length=1024)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='persistence.bankconnectionmodel')),
            ],
            options={
                'db_table': 'account_mappings',
            },
        ),
        migrations.CreateModel(
            name='ImportSessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('tan_required', 'TAN Required'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('challenge_text', models.TextField(blank=True, default='')),
                ('client_state_blob', models.BinaryField(blank=True, null=True)),
                ('dialog_state_blob', models.BinaryField(blank=True, null=True)),
                ('tan_state_blob', models.BinaryField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('imported_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persistence.bankconnectionmodel')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persistence.accountmappingmodel')),
            ],
            options={
                'db_table': 'import_sessions',
            },
        ),
    ]
