# Generated by Django 6.0.4 on 2026-04-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, default='')),
                ('body_template', models.TextField(default='{"event": "$event", "session_id": "$session_id", "challenge_text": "$challenge_text", "tan_submit_url": "$tan_submit_url"}')),
                ('method', models.CharField(choices=[('POST', 'POST'), ('PUT', 'PUT')], default='POST', max_length=10)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'webhook_config',
            },
        ),
    ]
