# Generated by Django 6.1.1 on 2026-09-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0002_webhookconfigmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsessionmodel',
            name='decoupled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importsessionmodel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importsessionmodel',
            name='resume_transaction_fetch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importsessionmodel',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
